//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDietManagerEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMacronutrient
    {
        public int UserMacronutrientsID { get; set; }
        public int Protein { get; set; }
        public int Carbohydrate { get; set; }
        public int Fat { get; set; }
        public int UserDietProfileID { get; set; }
    
        public virtual UsersDietProfile UsersDietProfile { get; set; }
    }
}
